import { FETCH_USERS_REQUEST, FETCH_USERS_SUCCESS, FETCH_USERS_FAILURE,
  FETCH_ADD_USER_REQUEST, FETCH_ADD_USER_SUCCESS, FETCH_ADD_USER_FAILURE,
  FETCH_EDIT_USER_REQUEST, FETCH_EDIT_USER_SUCCESS, FETCH_EDIT_USER_FAILURE,
  FETCH_CHANGE_PASSWORD_REQUEST, FETCH_CHANGE_PASSWORD_SUCCESS,
  FETCH_CHANGE_PASSWORD_FAILURE,
} from '../actions/users'
import { FETCH_LOGIN_REQUEST, FETCH_LOGIN_SUCCESS, FETCH_LOGIN_FAILURE,
  FETCH_TOKEN_LOGIN_REQUEST, FETCH_TOKEN_LOGIN_SUCCESS,
  FETCH_TOKEN_LOGIN_FAILURE, FETCH_FORGOT_PASSWORD_REQUEST,
  FETCH_FORGOT_PASSWORD_SUCCESS, FETCH_FORGOT_PASSWORD_FAILURE,
  FETCH_CONFIRM_EMAIL_REQUEST, FETCH_CONFIRM_EMAIL_SUCCESS,
  FETCH_CONFIRM_EMAIL_FAILURE, FETCH_LOGOUT_REQUEST, FETCH_LOGOUT_SUCCESS,
  FETCH_LOGOUT_FAILURE
} from '../actions/authedUser'
import { FETCH_ACCESS_TOKEN_REQUEST, FETCH_ACCESS_TOKEN_SUCCESS,
  FETCH_ACCESS_TOKEN_FAILURE
} from '../actions/csrfAccessToken'
import { FETCH_REFRESH_TOKEN_REQUEST, FETCH_REFRESH_TOKEN_SUCCESS,
  FETCH_REFRESH_TOKEN_FAILURE
} from '../actions/csrfRefreshToken'
import { FETCH_MAIL_CONTACT_REQUEST, FETCH_MAIL_CONTACT_SUCCESS,
  FETCH_MAIL_CONTACT_FAILURE
} from '../actions/contact'

/**
 * Updates isFetching state in store each
 * time an action in switch case is called
 *
 * @param {Object} state - isFetching
 * @param {Object} action
 * @return {Object} state - new isFetching
 */
const isFetching = (state = false, action) => {
  switch(action.type) {
    case FETCH_USERS_REQUEST :
    case FETCH_ADD_USER_REQUEST :
    case FETCH_LOGIN_REQUEST :
    case FETCH_TOKEN_LOGIN_REQUEST :
    case FETCH_FORGOT_PASSWORD_REQUEST :
    case FETCH_CHANGE_PASSWORD_REQUEST :
    case FETCH_CONFIRM_EMAIL_REQUEST :
    case FETCH_EDIT_USER_REQUEST :
    case FETCH_LOGOUT_REQUEST :
    case FETCH_ACCESS_TOKEN_REQUEST :
    case FETCH_REFRESH_TOKEN_REQUEST :
    case FETCH_MAIL_CONTACT_REQUEST :
      return true
    case FETCH_USERS_SUCCESS :
    case FETCH_USERS_FAILURE :
    case FETCH_ADD_USER_SUCCESS :
    case FETCH_ADD_USER_FAILURE :
    case FETCH_LOGIN_SUCCESS :
    case FETCH_LOGIN_FAILURE :
    case FETCH_TOKEN_LOGIN_SUCCESS :
    case FETCH_TOKEN_LOGIN_FAILURE :
    case FETCH_FORGOT_PASSWORD_SUCCESS :
    case FETCH_FORGOT_PASSWORD_FAILURE :
    case FETCH_CHANGE_PASSWORD_SUCCESS :
    case FETCH_CHANGE_PASSWORD_FAILURE :
    case FETCH_CONFIRM_EMAIL_SUCCESS :
    case FETCH_CONFIRM_EMAIL_FAILURE :
    case FETCH_EDIT_USER_SUCCESS :
    case FETCH_EDIT_USER_FAILURE :
    case FETCH_LOGOUT_SUCCESS :
    case FETCH_LOGOUT_FAILURE :
    case FETCH_ACCESS_TOKEN_SUCCESS :
    case FETCH_ACCESS_TOKEN_FAILURE :
    case FETCH_REFRESH_TOKEN_SUCCESS :
    case FETCH_REFRESH_TOKEN_FAILURE :
    case FETCH_MAIL_CONTACT_SUCCESS :
    case FETCH_MAIL_CONTACT_FAILURE :
      return false
    default :
      return state
  }
}

export default isFetching
